title: Samael's
markdown: kramdown

# for atom feed
author:
  name: Saammaaeel
  email: codenamesamael@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
